from model.MF import MF
from model.LightGCN import LightGCN
from model.KNN import KNN
from model.DUIF import DUIF
from model.DeepMusic import DeepMusic
from model.MTPR import MTPR
from model.VBPR import VBPR
from model.AMR import AMR
from model.GAR import GAR
from model.ALDI import ALDI
from model.CLCRec import CLCRec
from model.LARA import LARA
from model.CCFCRec import CCFCRec
from model.DropoutNet import DropoutNet
from model.Heater import Heater
from model.MetaEmbedding import MetaEmbedding
from model.GoRec import GoRec
